DISCORD_BOT_TOKEN = "<REDACTED>"
DISCORD_DEVELOPMENT_SERVER = <"INT" REDACTED>

TWITTER_CLIENT_ID = "<REDACTED>"
TWITTER_CLIENT_SECRET = "<REDACTED>"
TWITTER_ACCESS_TOKEN = "<REDACTED>"
TWITTER_ACCESS_TOKEN_SECRET = "<REDACTED>"
TWITTER_API_KEY = "<REDACTED>"
TWITTER_API_KEY_SECRET = "<REDACTED>"
TWITTER_BEARER_TOKEN = "<REDACTED>"
TWITTER_REDIRECT_URI = "https://socialbot.online/link-twitter"

POINTS_SHOP_WALLET = "rJWCidBvGqGs6cAJgSdre1545ZeuExWHgc"
